### ISSUE TITLE
multi-process support

### ISSUE THREAD

**Issue by WencongXiao** [NVIDIA/cuda-checkpoint#1]
It is great to see the cuda checkpointing project! I really like it. :)

Regarding the current limitation about cuda-checkpoint,
``acts upon a single process, not a process tree``.

Do you have any plan to support that? I think this feature is critical to make cuda-ckpt a practical toolkit. 

Thanks,
Wencong

**Comment by sgurfinkel** [comment]
We are working on this!

**Comment by jesus-ramos** [comment]
Multi process support has been merged into CRIU if you'd like to give it a shot
