### ISSUE TITLE
The version of CUDA supported

### ISSUE THREAD

**Issue by IndependenceSDS** [NVIDIA/cuda-checkpoint#2]
What CUDA versions are supported by this project? Can it be used on CUDA12.4？

**Comment by rst0git** [comment]
> Can it be used on CUDA12.4？

It works with 12.4.

**Comment by IndependenceSDS** [comment]
您好，我是cgg的邮箱小管家！已收到您的来信！主人会尽快回复哒！请耐心等待哟！

**Comment by IndependenceSDS** [comment]
> > Can it be used on CUDA12.4？
> 
> It works with 12.4.

thanks

**Comment by ayushr2** [comment]
@rst0git I tried compiling the example provided in this repo with CUDA 12.3 and 12.2 but with driver version `570.86.15`. And it seemed to work.

So is the requirement regarding the CUDA version, or the driver version, or both? From my local experimentation, it seems like the requirement is driver version only. Is that true?
