### ISSUE TITLE
In what environment will example.sh work?

### ISSUE THREAD

**Issue by Hitigerzzz** [NVIDIA/cuda-checkpoint#3]
I encountered some issues while trying to run example.sh, can anyone provide an environment configuration for example.sh to work properly? Thanks.

1.  Error (criu/cr-restore.c:1480): 1959 killed by signal 11: Segmentation fault
Error (criu/cr-restore.c:2447): Restoring FAILED.

The error command is:
`criu restore --shell-job --restore-detached --images-dir demo`

The environment is:
driver: 550.54.14
cuda: 12.4
gpu: NVIDIA GeForce RTX 3090
os: Ubuntu 22.04.4 LTS
kernel: 5.15.0-101-generic
criu: 3.16.1

2. Error toggling CUDA in process ID 2379: "initialization error"

The error command is:
`cuda-checkpoint --toggle --pid $PID`

The env is:
driver: 550.54.14
cuda: 12.4
gpu: NVIDIA A10
os: Ubuntu 18.04.6 LTS
kernel: 4.15.0-213-generic
criu: 3.6

**Comment by rst0git** [comment]
It looks like the version of CRIU on your system is too old (https://github.com/checkpoint-restore/criu/issues/1695).

@Hitigerzzz Would you be able to install newer version?
https://launchpad.net/~criu/+archive/ubuntu/ppa

**Comment by Hitigerzzz** [comment]
> It looks like the version of CRIU on your system is too old ([checkpoint-restore/criu#1695](https://github.com/checkpoint-restore/criu/issues/1695)).
> 
> @Hitigerzzz Would you be able to install newer version? https://launchpad.net/~criu/+archive/ubuntu/ppa

version 3.19 works. Thank you!
