### ISSUE TITLE
CRIU dump failed since it failed to dump external device file

### ISSUE THREAD

**Issue by zobinHuang** [NVIDIA/cuda-checkpoint#7]
Hi NVIDIA folks, thanks for this wonderful transparent C/R tool, really helpful!

I encountered an issue when `criu dump` a pytorch process within a container, after using this tool to suspend the CUDA state.

the commands I used are:

```bash
$ cuda-checkpoint --toggle --pid $pid
$ criu dump --tree $pid --images-dir $ckpt_dir --shell-job --display-stats
```

The error message from the `criu dump` command looks like:

```bash
Warn  (criu/kerndat.c:1593): CRIU was built without libnftables support
Error (criu/files-ext.c:94): Can't dump file 17 of that type [20666] (chr 195:255)
Error (criu/cr-dump.c:1674): Dump files (pid: 406) failed with -1
Error (criu/cr-dump.c:2098): Dumping FAILED.
```

The software environment I met this issue is:

* Docker image: [nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04](https://hub.docker.com/layers/nvidia/cuda/11.3.1-cudnn8-devel-ubuntu20.04/images/sha256-278b6f43436029c8fa7b4905970457156774178b99509aa753b08547fb721cd9?context=explore)
* CUDA: 11.3
* nvidia driver: 550.54.1
* criu: 3.19

Looks like it's due to the `criu` failed to dump an external file, and this file seems to be a nvidia device file

```bash
$ grep 195 /proc/devices  
195 nvidia
195 nvidia-modeset
195 nvidiactl
```

Does anyone has any comment on this issue? Thanks for any suggestion :-)

**Comment by rst0git** [comment]
> I encountered an issue when criu dump a pytorch process within a container

@zobinHuang There is another GitHub issue about checkpointing PyTorch with more information about this problem: https://github.com/NVIDIA/cuda-checkpoint/issues/4.

**Comment by fals** [comment]
@rst0git is this even fixed in criu? The bug was closed but no code changes. I'm trying to checkpoint a LLM and the same error 

```bash
[root@ip-192-168-94-88 var]# cat llm2/criu-dump.log
Error (criu/files-ext.c:94): Can't dump file 9 of that type [20666] (chr 195:255)
Error (criu/cr-dump.c:1698): Dump files (pid: 100773) failed with -1
Error (criu/cr-dump.c:2128): Dumping FAILED.
```

I'm using the version 4.2 of criu.

**Comment by rst0git** [comment]
@fals The error in this issue occurs with driver version 550, and has been fixed in the newer versions: https://github.com/NVIDIA/cuda-checkpoint/issues/4#issuecomment-2616458251

**Comment by fals** [comment]
> [@fals](https://github.com/fals) The error in this issue occurs with driver version 550, and has been fixed in the newer versions: [#4 (comment)](https://github.com/NVIDIA/cuda-checkpoint/issues/4#issuecomment-2616458251)

So this is what my `nvidia-smi` outputs, so I'm in very late version, and I'm trying to checkpoint a quite new [OSS llm](https://hub.docker.com/layers/vllm/vllm-openai/v0.11.1/images/sha256-e4896bdb93ffab61032f8992624928c198363b5085a0c9ac2af8a7f992de89a2).

```bash
 NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0 
```

**Comment by rst0git** [comment]
@fals Would it be possible to confirm if the CUDA Plugin is installed in `/usr/lib/criu/cuda_plugin.so` and the `cuda-checkpoint` utility is available in `PATH`? It would also be helpful to share the full CRIU log file.

**Comment by fals** [comment]
> /usr/lib/criu/cuda_plugin.so

Ok after you giving hints and exhaustive trial and error adding new params I could dump the LLM I shared. TL;DR; The command I had to use should include the plugin path and it only worked putting `cuda-checkpoint` binary in the same directory as criu's, PATH did not work at all. Thank you for the hints helped a lot!

Here's the full command for reference
```bash
 criu dump \
    --images-dir llm2 \
    --tree  $PID \
    --log-file criu-dump.log \
    --external 'mnt[]:sm' \
    --shell-job \
    --display-stats \
    --skip-in-flight \
    --link-remap \
    --tcp-established \
    --libdir /usr/local/lib/criu
```
