### ISSUE TITLE
The release time of the complete tool

### ISSUE THREAD

**Issue by IndependenceSDS** [NVIDIA/cuda-checkpoint#9]
GTC2024 mentioned that  a complete checkpoint tool will release in the first half of this year. Is there any change in this plan? When can the complete tool be released approximately?

**Comment by jesus-ramos** [comment]
It's currently available with the latest release of r555. If you already have the cuda-checkpoint utility with an r555 driver the new functionality will be available (cuda-checkpoint -h will show new --action flag).

I currently have a PR open to merge support for this into CRIU https://github.com/checkpoint-restore/criu/pull/2416

If you place cuda-checkpoint on your $PATH and have an r555 driver and are willing to build CRIU yourself you can try it out.

**Comment by IndependenceSDS** [comment]
> It's currently available with the latest release of r555. If you already have the cuda-checkpoint utility with an r555 driver the new functionality will be available (cuda-checkpoint -h will show new --action flag).
> 
> I currently have a PR open to merge support for this into CRIU [checkpoint-restore/criu#2416](https://github.com/checkpoint-restore/criu/pull/2416)
> 
> If you place cuda-checkpoint on your $PATH and have an r555 driver and are willing to build CRIU yourself you can try it out.

thanks!
